name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: braboobssiere/Smart-AutoClicker_copy
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Add upstream
        run: git remote add upstream https://github.com/Nain57/Smart-AutoClicker.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/master
        continue-on-error: true

      - name: Push changes
        if: success()
        run: git push origin main

      - name: Create pull request
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge conflicts from upstream'
          branch: sync-upstream
          title: 'Sync with upstream'
          body: 'This pull request contains updates from the upstream repository.'
