name: Auto-Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # daily sync
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: braboobssiere
          base: master
          head: master
          merge_method: rebase
