name: Auto-Sync Fork

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 * * *'  # daily sync
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: braboobssiere
          base: master
          head: master
          repo: Smart-AutoClicker_copy
          merge_method: rebase
